export const themes: Record<ThemeName, ThemeColors> = {
    light: {
        text: 'text-neutral-900',
        bg: 'bg-neutral-100',
        bgSecondary: 'bg-white',
        border: 'border border-neutral-200',
        rounded: 'rounded-lg',
        font: 'font-[Inter]',
        invertedText: 'text-neutral-100',
        invertedBg: 'bg-neutral-900',
        hover: {
            bg: 'hover:bg-neutral-900',
            text: 'hover:text-neutral-100',
        },
        placeholder: 'placeholder:text-neutral-900/70',
    },
    dark: {
        text: 'text-neutral-100',
        bg: 'bg-neutral-950',
        bgSecondary: 'bg-neutral-900',
        border: 'border border-neutral-800',
        rounded: 'rounded-none',
        font: 'font-[Inter]',
        hover: {
            bg: 'hover:bg-white',
            text: 'hover:text-black',
        },
        placeholder: 'placeholder:text-neutral-100/70',
        invertedText: 'text-neutral-950',
        invertedBg: 'bg-neutral-100',
    },
    ice: {
        text: 'text-slate-800',
        bg: 'bg-[#86b4c9]',
        bgSecondary: 'bg-[#eaf6fc]/80 backdrop-blur-sm',
        border: 'border border-white/60',
        rounded: 'rounded-md',
        font: 'font-[Inter]',
        hover: {
            bg: 'hover:bg-white/20',
            text: 'hover:text-white',
        },
        placeholder: 'placeholder:text-white/70',
        invertedText: 'text-slate-800',
        invertedBg: 'bg-[#86b4c9]',
    },
    water: {
        text: 'text-white',
        bg: 'bg-gradient-to-br from-blue-500 to-blue-700',
        bgSecondary: 'bg-blue-600/80 backdrop-blur-sm',
        border: 'border border-blue-400/30',
        rounded: 'rounded-3xl',
        font: 'font-[Inter]',
        hover: {
            bg: 'hover:bg-blue-400/20',
            text: 'hover:text-white',
        },
        placeholder: 'placeholder:text-white/70',
        invertedText: 'text-blue-600',
        invertedBg: 'bg-white/90',
    },
    earth: {
        text: 'text-stone-900',
        bg: 'bg-orange-50',
        bgSecondary: 'bg-white',
        border: 'border border-stone-200',
        rounded: 'rounded-lg',
        font: 'font-serif',
        hover: {
            bg: 'hover:bg-green-600',
            text: 'hover:text-[#422211]',
        },
        placeholder: 'placeholder:text-green-600/70',
        invertedText: 'text-[#422211]',
        invertedBg: 'bg-green-600',
    },
    fire: {
        text: 'text-black',
        bg: 'bg-red-700',
        border: 'border border-black',
        hover: {
            bg: 'hover:bg-black',
            text: 'hover:text-red-500',
        },
        placeholder: 'placeholder:text-black/70',
        invertedText: 'text-red-500',
        invertedBg: 'bg-black',
        bgSecondary: '',
        rounded: '',
        font: '',
    },
    rain: {
        text: 'text-stone-900',
        bg: 'bg-gray-400',
        border: 'border border-stone-900',
        hover: {
            bg: 'hover:bg-stone-800',
            text: 'hover:text-gray-400',
        },
        placeholder: 'placeholder:text-stone-900/70',
        invertedText: 'text-gray-400',
        invertedBg: 'bg-stone-800',
        bgSecondary: '',
        rounded: '',
        font: '',
    },
    wind: {
        text: 'text-stone-700',
        bg: 'bg-gray-100',
        border: 'border border-stone-700',
        hover: {
            bg: 'hover:bg-stone-700',
            text: 'hover:text-gray-100',
        },
        placeholder: 'placeholder:text-stone-700/70',
        invertedText: 'text-gray-100',
        invertedBg: 'bg-stone-700',
        bgSecondary: '',
        rounded: '',
        font: '',
    },
    space: {
        text: 'text-white',
        bg: 'bg-black',
        border: 'border border-white',
        hover: {
            bg: 'hover:bg-white',
            text: 'hover:text-black',
        },
        placeholder: 'placeholder:text-white/70',
        invertedText: 'text-black',
        invertedBg: 'bg-white',
        bgSecondary: '',
        rounded: '',
        font: '',
    },
};
