export const workExperience: WorkExperience = {
    company: 'VG Meats',
    role: 'Lead Developer',
    period: '2022 - Present',
    responsibilities: ['Developed an ERP system', 'Built data pipelines', 'Automated repetitive workflows'],
    technologies: [
        { logo: '/react.svg', name: 'react-logo' },
        { logo: '/django.svg', name: 'django-logo' },
        { logo: '/google-cloud.svg', name: 'react-logo' },
        { logo: '/python.svg', name: 'python-logo' },
        { logo: '/vercel.svg', name: 'vercel-logo' },
        { logo: '/html.svg', name: 'html-logo' },
        { logo: '/css.svg', name: 'css-logo' },
        { logo: '/javascript.svg', name: 'javascript-logo' },
        { logo: '/mysql.svg', name: 'mysql-logo' },
        { logo: '/tailwind.svg', name: 'tailwind-logo' },
        { logo: '/docker.svg', name: 'docker-logo' },
    ],
    hasReferences: true,
    border: 'border-gray-200',
    bgSecondary: 'bg-white',
};
